---
apiVersion: v1
kind: Pod
metadata:
  name: toolbox
spec:
  containers:
    - name: runtime
      image: giantswarm/tiny-tools
      command:
        - sleep
        - infinity
      volumeMounts:
        - mountPath: "/mnt"
          name: data-pv-storage
  volumes:
    - name: data-pv-storage
      persistentVolumeClaim:
        claimName: data-pv-claim
